Clean up CI system
TODO: I might want a way to verify the latest PAUSE'd version is working

diff --git a/.github/workflows/unix.yml b/.github/workflows/unix.yml
--- a/.github/workflows/unix.yml
+++ b/.github/workflows/unix.yml
@@ -34,9 +34,17 @@ jobs:
           ~/perl5/perlbrew/perls/cache-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}/bin/perl -V
           
           ~/perl5/perlbrew/perls/cache-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}/bin/perl Build.PL
+          
           ./Build test --verbose
           
-          ~/perl5/perlbrew/perls/cache-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}/bin/perl -e 'print $^V' > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
+          command1_exit_code=$?
+          if [ $command1_exit_code -eq 0 ]; then
+            ~/perl5/perlbrew/perls/cache-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}/bin/perl -V > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
+            command2_exit_code=$?
+          else
+            echo "Error!" > test-output-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
+            exit $command1_exit_code
+          fi
         shell: bash
       - name: Upload results as artifact
         uses: actions/upload-artifact@v4.0.0
